platform:
    - x86

environment:
  global:
    CYG_ROOT: C:/cygwin
    CYG_CACHE: C:/cygwin/var/cache/setup
    CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
  matrix:
    -
      CYG_ARCH: x86

init:
    - 'echo System architecture: %PLATFORM%'

install:
    - 'appveyor DownloadFile http://cygwin.com/setup-%CYG_ARCH%.exe -FileName setup.exe'
    - 'setup.exe -qnNdO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P make -P git -P gcc-core -P ocaml -P ocaml-camlp4 -P ocaml-compiler-libs -P curl -P libncurses-devel -P m4 -P unzip >NUL'
    - 'setup.exe -qnNdO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P libmpfr-devel -P patch -P flexdll >NUL'
    - '%CYG_ROOT%/bin/bash -lc "cygcheck -dc cygwin"'

build_script:
    - 'setup_opam.cmd'
    - '%CYG_ROOT%/bin/bash -lc "opam init -y -a https://github.com/Chris00/opam-repository"'
    - '%CYG_ROOT%/bin/bash -lc "opam install -y ocamlfind"'
    - '%CYG_ROOT%/bin/bash -lc "opam install -y -v ocamlmod"'

cache:
    - opam -> setup_opam.cmd

